services:
  wpapp:
    build:
      context: .
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - .:/var/www
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
    networks:
      - litepress

  # Add Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - litepress
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  litepress:
    driver: bridge

volumes:
  redis-data:
    driver: local